name: emilekbul
description: "A new Flutter project."

publish_to: 'none' 

version: 1.3.1+8

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  google_generative_ai: ^0.4.7
  provider: ^6.0.5
  animated_text_kit: ^4.2.3
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  intl: ^0.20.2
  package_info_plus: ^8.3.0
  http: ^1.2.1
  html: ^0.15.4
  url_launcher: ^6.2.5
  google_mobile_ads: ^6.0.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.0
  android_intent_plus: ^5.3.0
  device_info_plus: ^9.1.0
  permission_handler: 12.0.1
  cupertino_icons: ^1.0.8
  firebase_core_dart: ^1.0.1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.4 
  flutter_test:
    sdk: flutter
  

  
  flutter_lints: ^6.0.0


flutter_icons:
  android: true
  ios: true
  image_path_android: "lib/assets/emilekbul.png"
  adaptive_icon_foreground: "lib/assets/emilekbul.png"
  image_path_ios: "lib/assets/emilekbul.png"
  adaptive_icon_background: "#00000000"

flutter:

  uses-material-design: true

 
  assets:
    - lib/assets/
    - .env
  
  
