// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnuBVbH1k3BgeSyFy3u7zgh_z8kaNVyMg',
    appId: '1:561094034943:web:5caaac85deee8d6513d3ca',
    messagingSenderId: '561094034943',
    projectId: 'emilekbul-c292c',
    authDomain: 'emilekbul-c292c.firebaseapp.com',
    storageBucket: 'emilekbul-c292c.firebasestorage.app',
    measurementId: 'G-19R1XF456W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaH82UqOFeNkEOi2dFgstOAgeKwblSaf4',
    appId: '1:561094034943:android:e10e4a2ae28424b213d3ca',
    messagingSenderId: '561094034943',
    projectId: 'emilekbul-c292c',
    storageBucket: 'emilekbul-c292c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwILjXtX1iPBowxAGucJ2pcd8UzXRV5ho',
    appId: '1:561094034943:ios:d4d466705741abe213d3ca',
    messagingSenderId: '561094034943',
    projectId: 'emilekbul-c292c',
    storageBucket: 'emilekbul-c292c.firebasestorage.app',
    iosBundleId: 'com.example.emilekbul',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwILjXtX1iPBowxAGucJ2pcd8UzXRV5ho',
    appId: '1:561094034943:ios:d4d466705741abe213d3ca',
    messagingSenderId: '561094034943',
    projectId: 'emilekbul-c292c',
    storageBucket: 'emilekbul-c292c.firebasestorage.app',
    iosBundleId: 'com.example.emilekbul',
  );
}
